["$globals"]
shell = "bash"
version = "5.2"

["$globals".vars]
poetry_sync = "--sync"

[install]
phony = true
keep_ts = true
requires = [
    "poetry.lock",
]
commands = [
    "poetry install ${poetry_sync} ${poetry_extra}",
]

[format]
phony = true
requires = [
    "install",
]
commands = [
    "black .",
    "ruff --fix-only .",
]

[lint]
phony = true
requires = [
    "install",
]
commands = [
    "black --check .",
    "poetry lock --check",
    "ruff .",
    "mypy .",
]

[tests]
phony = true
requires = [
    "install",
]
commands = [
    "pytest ${pytest_args} ${pytest_path} ${.extra}",
]

["docs/source"]
exists_only = true
recursive = true

[docs]
alias = "documentation"

[documentation]
phony = true
keep_ts = true
requires = [
    "docs/source",
]
commands = [
    "sphinx-build -b html docs/source docs/build",
]

[clean-docs]
phony = true
commands = [
    "rm -rf docs/build/",
    "rm -f .yamk/documentation",
]

["poetry.lock"]
update = true
requires = [
    "pyproject.toml",
]
commands = [
    "poetry lock",
]
